const Routes = {
  APP_INTRO: 'APP_INTRO',
  LOADING: 'LOADING',
  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  MAIN_STACK: 'MAIN_STACK',
  USER_DETAIL: 'USER_DETAIL',
  USERS: 'USERS',
  RESOURCES: 'RESOURCES',
};

export default Routes;
